vault_address               = "http://127.0.0.1:8200"
vault_secret_engine         = "gcp-sa-impersonation"
impersonator_static_account = "impersonator-sa"
executor_service_account    = "executor-sa@hale-sequence-386314.iam.gserviceaccount.com"
project_id                  = "hale-sequence-386314"